from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
import os


def generate_pdf(data: dict):

    os.makedirs("generated_reports", exist_ok=True)

    filename = f"generated_reports/report_{data['village']}.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    elements = []

    title = Paragraph(
        "<b>GeoInsight AI Land Analysis Report</b>",
        styles["Title"]
    )

    elements.append(title)

    elements.append(Paragraph("<br/><br/>", styles["Normal"]))

    table_data = [
    ["Field", "Value"],

    ["Village", data["village"]],
    ["District", data["district"]],
    ["State", data["state"]],
    ["Date", data["date"]],

    ["Latitude", data["latitude"]],
    ["Longitude", data["longitude"]],

    ["Total Area (ha)", f"{data['total_area']:.2f}"],

    ["Vegetation (ha)", f"{data['vegetation']:.2f}"],
    ["Water (ha)", f"{data['water']:.2f}"],
    ["Built-up (ha)", f"{data['builtup']:.2f}"],
    ["Barren (ha)", f"{data['barren']:.2f}"],

    ["NDVI", f"{data['ndvi']:.4f}"],
    ["NDWI", f"{data['ndwi']:.4f}"],
    ["NDBI", f"{data['ndbi']:.4f}"],

    ["AI Prediction", data["prediction"]],
    ["AI Confidence", f"{data['confidence']:.2f}%"],

    ["Recommendation", data["recommendation"]],
]

    table = Table(table_data, colWidths=[2.5 * inch, 3 * inch])

    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkgreen),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

        ("GRID", (0, 0), (-1, -1), 1, colors.black),

        ("BACKGROUND", (0, 1), (-1, -1), colors.beige),

        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
    ]))

    elements.append(table)

    elements.append(Paragraph("<br/><br/>", styles["Normal"]))

    footer = Paragraph(
        "<b>Generated by GeoInsight AI</b><br/>"
        "AI-based Land Mapping & Analysis System<br/>"
        "VIT Bhopal University",
        styles["Normal"]
    )

    elements.append(footer)
    doc.build(elements)

    return filename
